### PR TITLE
Fix Import Headers for 0.40

### PR DESCRIPTION
**Pull request by K-Leon**

### CODE REVIEW

**Comment by andpor** [comment]
Won't this make the library incompatible with earlier versions of RN? Anything that can be done to keep the compatibility (a lot of folks still using older RN versions)...

**Comment by thedjinn** [comment]
Yes it does break older versions as mentioned in the RN release notes. But you can mention in the readme file that people running 0.39 or earlier should use the previous package version.

Anyway, without merging you prevent new projects from adopting your package which would be a shame.

**Comment by andpor** [comment]
I will release the new version and then merge your pull request.

**Comment by andpor** [comment]
Thank you!

**Comment by K-Leon** [comment]
Thx!

**Pull request merged**
