### PR TITLE
Add documentation for using android-native platform

### LINKED ISSUE #371: Document how to use FTS5 on Android
Searching through Github issues, [it looks like](https://github.com/andpor/react-native-sqlite-storage/issues/344#issuecomment-484293027)  FTS5 is unsupported on Android.

[Here](https://github.com/andpor/react-native-sqlite-storage/issues/310#issuecomment-469357373) @brodybits references a repo that can be built to produce FTS5-supporting libs.

For this issue, I'd like:
- FTS5 support out-of-the-box on Android
 _-or-_
- An explanation as to why it's not offered, and advice how to work around it.

Would you _like_ to support it, or are you specifically avoiding it for some reason? (would you accept contributions enable it?)

### LINKED ISSUE #389: How to install on RN 0.60> && docs?
As we all know React Native autolink feature handles the linking operations. But should we still have to do install sequence, that on the readme? (If we have to please update the readme)
I tried to manually link but it gives multiple errors..

And is there any documentation for fully operation .etc?

**EDIT:** Autolink feature is enough, but readme isn't tell about it. If we can update readme it will be more helpful for avoiding mind confusing

### PR DESCRIPTION
**Pull request by gvanderclay**
Closes #389 
Closes #371 
Closes #377

### CODE REVIEW

**Comment by gvanderclay** [comment]
Bump @andpor

**Comment by andpor** [comment]
Thanks!

**Comment by andpor** [comment]
Merged. Will cut release tomorrow. Thanks!

**Comment by andpor** [comment]
Published as part of 5.0.0
Thank you!

**Pull request merged**
