### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Grom-S**
Looks like you have incorrect path in android installation instructions

### CODE REVIEW

**Comment by jawwad22** [comment]
yes, kindly merge it branch

**Comment by andpor** [comment]
Can you please resolve conflicts before I merge this.

**Comment by lkoehl** [comment]
Should also be closed by #385

**Comment by andpor** [comment]
@Grom-S closing this PR without merging as it seems to be resolved already. Can you confirm?

**Pull request closed without merging**
