### PR TITLE
Allow users to explicitly specify the original asset DB file.

### PR DESCRIPTION
**Pull request by boazy**
This pull requests allow users to put their pre-populated assets everywhere, and not just in legacy cordova-style assets directories.

### CODE REVIEW

**Comment by andpor** [comment]
@brodybits Chris - any thoughts about the second checkin - read only file ?

**Comment by brodybits** [comment]
Hmm. The read-only database asset is a nice feature for iOS but I would consider it risky to introduce features that work on only one platform.

Personally, I would wrap the read-only db asset feature in #ifdef ... #endif so that it is disabled by default. A user may *optionally* define the macro somewhere if s/he wants this feature.

**Comment by andpor** [comment]
@brodybits Chris, so I understand. Why do you think this is iOS only. It seems that sqlite3_open_v2 is supported on Android builds as well? Or is it that it is not supported by your native impl?

**Comment by brodybits** [comment]
In iOS, it is possible to treat a an asset as a read-only file. But in Android the asset files are stored in compressed format, and you have to use an API call to extract the asset file before you can access its contents.

The second commit in this PR supports reading from a read-only database asset for iOS but *not* for Android.

I personally like to avoid changes that only work for one platform since they introduce the potential for app portability issues.

**Comment by andpor** [comment]
@brodybits Chris I agree. First change is not a merge material since it introduces an backward incompatible functional modification. It is due to implementation but the concept is neat so I implemented it into the module in a backward compatible fashion,  allowing the asset to be pulled from 3 different locations rather than just www. @boazy - thanks for contributing.

**Pull request closed without merging**
