### PR TITLE
Resolve npm audit moderate vulnerability

### PR DESCRIPTION
**Pull request by alpha0010**
Remove unused obsolete dependency.

### CODE REVIEW

**Comment by alpha0010** [comment]
@andpor Do you have a chance to look at this?  It would be great to handle so npm stops reporting vulnerabilities.

**Comment by alpha0010** [comment]
@andpor Could you tag a new release, to enable this to take effect?

**Comment by Robinfr** [comment]
@andpor can this be released?

**Comment by andpor** [comment]
will take care of it next week

**Comment by andpor** [comment]
@Robinfr this was release as part of 3.3.9 already. in April...

**Comment by Robinfr** [comment]
Clearly not... https://www.npmjs.com/package/react-native-sqlite-storage

**Pull request merged**
