### PR TITLE
updated readme for react native 0.18

### PR DESCRIPTION
**Pull request by christiansaiki**
The react native 0.18 version has different code base than the one
that is presented in the current readme docs.

### CODE REVIEW

**Comment by andpor** [comment]
@christiansaiki  - hi there...I am not able to find any references to a class called ReactActivity..any idea?

**Comment by christiansaiki** [comment]
@andpor I haven't found a doc for this, but they have changed the MainActivity.java file.
I have found a simmilar issue here https://github.com/rebeccahughes/react-native-device-info/issues/17
This thread helped me to install your package properly.

**Comment by christiansaiki** [comment]
I just saw how this library suggests the proper installation of it
https://github.com/rebeccahughes/react-native-device-info
I should have done a better job by putting the new and old way.
If you want I can do this.

**Comment by andpor** [comment]
Have you tested this new approach? I cannot find any references to ReactActivity ? Where is it coming from?

**Comment by andpor** [comment]
Yes, please do submit a revised PR with original and new Android instructions...

**Comment by andpor** [comment]
@christiansaiki - I updated the README file to reflect the alternative approach.

**Pull request closed without merging**
