### PR TITLE
Android Database plugin system v2

### PR DESCRIPTION
**Pull request by dryganets**
Database abstracted by adapter layer. It is possible to enable encryption via sqlite cipher. Once little-glue implementation of the adapter will be ready it will be possible to remove android-native project and get rid of code duplication burden.

The adapter code is here:
https://github.com/dryganets/sqlite-adapter

It is published in maven central repository.

### CODE REVIEW

**Comment by dryganets** [comment]
@andpor this should be way easier to review as it has less structural changes.
You could see now how straightforward the implementation is.

**Comment by andpor** [comment]
I do not understand the rationale for removing android native ?

**Comment by dryganets** [comment]
@andpor, I'm not removing it yet.

The rationale is that currently if you want to add a new feature to the code base you have to add the same code to two different android projects.

A lot of code duplication and easy to break/forget something.

I'll implement the provider for liteglue once I got a couple of hours of free time and the code will look the same for all 3 libraries.

**Comment by dryganets** [comment]
Any chance for review/merge?
The changes to the code base are minimal here.

What I have as a dependency is just an adapter for sqlite API.
Implementations are straightforward.

**Comment by Guilmoraes** [comment]
Any chance for review/merge?

**Pull request closed without merging**
