### PR TITLE
Remove old rnpm for react-native 0.60

### PR DESCRIPTION
**Pull request by carlosroberto555**
I have folow this [migration guide](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide) for fix the rn60 warning
I don't have time to test this change yet, but I accept any feedbacks
#359

### CODE REVIEW

**Comment by brodybits** [comment]
Looks nice, I will try to test it later today.

I would favor that we keep the existing `rnpm` entry for now, so that people can continue using React Native pre-0.60 for a while.

**Comment by carlosroberto555** [comment]
I find this [part of migration guide](https://github.com/react-native-community/cli/blob/master/docs/projects.md#migrating-from-rnpm-configuration) and fixed the react-native.config.js

**Comment by carlosroberto555** [comment]
How we can do android link with `react-native link`?
Anybody has the answer?

**Comment by carlosroberto555** [comment]
> Looks nice, I will try to test it later today.
> 
> I would favor that we keep the existing `rnpm` entry for now, so that people can continue using React Native pre-0.60 for a while.

@brodybits I had read on migration guide, and see this info:

> "rnpm" is deprecated and support for it will be removed in next major version of the CLI.

It's not because react-native version, but the cli version, they are independent.
New versions of react-native-cli show this warning and version 2.0.0 is not compatible.
You can see more info [here](https://github.com/react-native-community/cli#compatibility).

**Comment by carlosroberto555** [comment]
@andpor any more changes request?

**Comment by crobinson42** [comment]
+1 can we help move this along in any way?

**Comment by carlosroberto555** [comment]
I'll create a another npm package for solve this problem.
This PR has more a month, and not had activity.

**Comment by crobinson42** [comment]
I don’t think creating another npm package solves any problems. That just spreads the community out more. This package has weekly downloads and many contributors in just think it would be helpful if the owner or maintainer was a little more active or delegated permissions for keeping PRs like this moving along for the library.

**Comment by carlosroberto555** [comment]
Yes not solve, it's only a idea
This workaround install from my fork directly.

```yarn add carlosroberto555/react-native-sqlite-storage```

I used on my personal project, and autolink works like a charm.

**Comment by andpor** [comment]
The PR is merged and released under 4.0.0 - sorry for delay, quite busy lately.

**Comment by mikehardy** [comment]
The burden on library maintainers for react-native 0.60 (both in their paying project work, and whatever libraries they maintain) is pretty serious, and it's vacation season - glad to see this merged but everyone be as helpful as you can in the libraries you use, pretty much like submitting the PR here (❤️) and being patient. Cheers

**Pull request merged**
