### PR TITLE
Support boolean type in params array

### PR DESCRIPTION
**Pull request by anativ**
When trying to send "boolean" as param the query hangs on iPhone
This updates allows to send booleans (true=1 / false=0)

### CODE REVIEW

**Comment by andpor** [comment]
Can you create an issue for this so I can link it up ?

**Comment by anativ** [comment]
There is issue #45 if you want I can open a new one

**Comment by anativ** [comment]
I opened a better issue for that #63

**Comment by brodybits** [comment]
This change could break Web SQL compatibility. When I tested with both my Cordova sqlite plugin and Web SQL I discovered that the Boolean values `false` and `true` are inserted as the string "false" and "true" values. My sqlite plugin uses the toString function to get the string value of non-primitive objects, and I suspect that Web SQL follows a similar strategy.

Cordova sqlite JavaScript code: https://github.com/litehelpers/Cordova-sqlite-storage/blob/storage-master/www/SQLitePlugin.js#L354-L358

test: https://github.com/litehelpers/Cordova-sqlite-storage/blob/storage-master/spec/www/spec/db-tx-value-bindings-test.js#L254-L284

**Comment by anativ** [comment]
@brodybits I understand  your concern but when sending a boolean as params on IOS device or Simulator (when not using debugger) the "executeSql" never returns (no success / error). thats not a valid option. 
Anyway "true" / "false" as strings is a bug even if Web SQL acts like that.
As I see it there are two options 
1. convert boolean to number (true=>1/false=>0) - this commit
2. return error 

Thanks

**Comment by brodybits** [comment]
I think it would be worse to return an error since it could really break code that was working for Web SQL. I think you have a good point to convert the boolean to a number since SQLite takes the same approach: https://www.sqlite.org/datatype3.html#section_2_1

**Comment by andpor** [comment]
This plugin will not divert in the fine SQL handling details from Cordova-sqlite-storage. It seems that currently the code is designed to handle boolean by converting the value to string using toString method.
https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L421-L429

I do not want to change this functionality for the reason that @brodybits has outlined but I am curious about the fact that executeSql never returns and provides no feedback. Can you send the sample query you are having problem with that would demonstrate the issue?

**Pull request merged**
