### PR TITLE
typescript typings added

### PR DESCRIPTION
**Pull request by dryganets**

### CODE REVIEW

**Comment by dryganets** [comment]
Probably not an ideal set of typings but should be a good start.

**Comment by dryganets** [comment]
Typings structured in the one would use the API.
the openDatabase call returns the interface giving access to the rest of the functionality.

The js code allows you to do more than that and returns the error, but I think this is the less confusing approach.

**Comment by dryganets** [comment]
@andpor, could you take a look.

I know typings work well.

At least it is a some starting point.
Shouldn't take much time to review.

**Comment by dryganets** [comment]
Any chance to get it merged?

**Comment by fhelwanger** [comment]
@dryganets Maybe you should try add it to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by dryganets** [comment]
probably you are right, will do it.
@andpor doesn't look at the PR's for a long time already :(

**Comment by dryganets** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24401

Please help to test it.
I did my best to wrap it correctly, but mistakes are possible.
I don't have a simple project handy to test all the cases correctly.

One of the differences is that I'm returning void in open and getting the database from the success callback.

I think it is an incorrect approach to work with DB object which might be invalid.
We are wrapping it manually in our code see:

https://github.com/Microsoft/NoSQLProvider/blob/master/src/CordovaNativeSqliteProvider.ts#L78-L83

Just let me know if you see some problems, PR's to DefenitelyTyped are always welcome!

**Pull request closed without merging**
