### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by somoso**
Add support for react-native link on the Android side (currently it only supports iOS)

### CODE REVIEW

**Comment by andpor** [comment]
How do we account for android-native?

**Comment by wizebin** [comment]
@andpor What can we do to help get this PR landed?

**Comment by andpor** [comment]
@wizebin - account for android native package in the PR.....

**Comment by wizebin** [comment]
> @wizebin - account for android native package in the PR.....

By android-native do you mean the subfolder in the src directory [here](https://github.com/andpor/react-native-sqlite-storage/tree/master/src/android-native)?

Currently the readme doesn't account for that android-native directory, this PR will automatically perform the steps laid out in the readme to link this library to android directory. Do you have a separate list of instructions to connect to the android-native subdirectory? 

If the native directory is commonly used you could consider releasing a separate npm package for that functionality, but it would be great to get this PR merged, there is very little value in leaving it the way it is.

**Comment by stoically** [comment]
Newer versions of RN don't even require to run `react-native link` anymore, the lib is automatically linked while `react-native run-android`, so it'd indeed be helpful to have this merged.

**Comment by andpor** [comment]
It's merged and released in 3.3.11

**Pull request merged**
